# Generated by Django 3.2.4 on 2021-06-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Pais')),
                ('nombrePais', models.CharField(max_length=50, verbose_name='Nombre del Pais')),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Identificacion', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Número de identificación')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('Telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
                ('Direccion', models.CharField(blank=True, max_length=9, null=True, verbose_name='Dirección')),
                ('Correo', models.CharField(blank=True, max_length=9, null=True, verbose_name='Correo')),
                ('Contraseña', models.CharField(blank=True, max_length=9, null=True, verbose_name='Contraseña')),
                ('Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
